name: Build Packer Image with HCP Packer
on:
  push:
    branches:
      - dev
      - main
    paths:
      - "packer/**"
      - ".github/workflows/build-packer-image.yml"
jobs:
  build:
    name: Build Supabase Packer Image with HCP
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prd' || 'dev' }}
    env:
      PACKER_LOG: 1
      TF_VAR_region: ${{vars.DO_REGION}}
      TF_VAR_droplet_image: ${{vars.DO_DROPLET_IMAGE}}
      TF_VAR_droplet_size: ${{vars.DO_DROPLET_SIZE}}
      TF_VAR_hcp_bucket_name: "${{vars.HCP_BUCKET_NAME}}-${{vars.DEPLOY_ENV}}"
      TF_VAR_github_actor: ${{github.actor}}
      TF_VAR_environment: ${{vars.DEPLOY_ENV}}
      # HCP Packer authentication
      HCP_CLIENT_ID: ${{secrets.HCP_CLIENT_ID}}
      HCP_CLIENT_SECRET: ${{secrets.HCP_CLIENT_SECRET}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "1.9.4" # Use a specific version or 'latest'
      - name: Initialize Packer
        working-directory: ./packer
        run: packer init .
      - name: Build and publish image with HCP Packer
        working-directory: ./packer
        run: |
          packer build \
            -var do_token="${{secrets.DO_API_TOKEN}}" \
            -var hcp_client_id="${{secrets.HCP_CLIENT_ID}}" \
            -var hcp_client_secret="${{secrets.HCP_CLIENT_SECRET}}" \
            .
      - name: Display HCP Packer build information
        run: |
          echo "Build complete. Image has been published to HCP Packer."
          echo "Bucket: ${{ vars.HCP_BUCKET_NAME }}"
